// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstanceInfo represents instance information for GUI consumption
 */
export class InstanceInfo {
    /**
     * Creates a new InstanceInfo instance.
     * @param {Partial<InstanceInfo>} [$$source = {}] - The source object to create the InstanceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("public_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_ip"] = "";
        }
        if (!("blueprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["blueprint"] = "";
        }
        if (!("bundle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundle"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["tags"] = {};
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstanceInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new InstanceInfo(/** @type {Partial<InstanceInfo>} */($$parsedSource));
    }
}

/**
 * ProjectInfo represents project overview information
 */
export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("student_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["student_count"] = 0;
        }
        if (!("running_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running_count"] = 0;
        }
        if (!("budget_used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budget_used"] = 0;
        }
        if (!("budget_total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budget_total"] = 0;
        }
        if (!("days_remaining" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["days_remaining"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

/**
 * UserInfo represents user role and permissions
 */
export class UserInfo {
    /**
     * Creates a new UserInfo instance.
     * @param {Partial<UserInfo>} [$$source = {}] - The source object to create the UserInfo.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["permissions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField3_0($$parsedSource["permissions"]);
        }
        return new UserInfo(/** @type {Partial<UserInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
