// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFRService provides the main service interface for the GUI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectToInstance initiates SSH connection for a student
 */
export function ConnectToInstance(username: string, project: string): $CancellablePromise<string> {
    return $Call.ByID(3900238179, username, project);
}

/**
 * GetProjectInfo returns project/class overview information
 */
export function GetProjectInfo(project: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(2992472392, project).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUserRole determines the current user's role and permissions
 */
export function GetUserRole(): $CancellablePromise<$models.UserInfo | null> {
    return $Call.ByID(3415882300).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListInstances returns all instances for the current user/project
 */
export function ListInstances(project: string): $CancellablePromise<($models.InstanceInfo | null)[]> {
    return $Call.ByID(2078346311, project).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * StartInstance starts a specific instance
 */
export function StartInstance(instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(4011197612, instanceName);
}

/**
 * StopInstance stops a specific instance
 */
export function StopInstance(instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(679314178, instanceName);
}

// Private type creation functions
const $$createType0 = $models.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UserInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.InstanceInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
