// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstanceInfo represents instance information for the frontend
 */
export class InstanceInfo {
    "name": string;
    "state": string;
    "public_ip": string;
    "blueprint": string;
    "bundle": string;
    "region": string;
    "tags": { [_: string]: string };

    /**
     * Extracted from instance name
     */
    "username": string;

    /** Creates a new InstanceInfo instance. */
    constructor($$source: Partial<InstanceInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("public_ip" in $$source)) {
            this["public_ip"] = "";
        }
        if (!("blueprint" in $$source)) {
            this["blueprint"] = "";
        }
        if (!("bundle" in $$source)) {
            this["bundle"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = {};
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InstanceInfo {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new InstanceInfo($$parsedSource as Partial<InstanceInfo>);
    }
}

/**
 * ProjectInfo represents project/class information
 */
export class ProjectInfo {
    "name": string;
    "student_count": number;
    "running_count": number;
    "budget_used": number;
    "budget_total": number;
    "days_remaining": number;

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("student_count" in $$source)) {
            this["student_count"] = 0;
        }
        if (!("running_count" in $$source)) {
            this["running_count"] = 0;
        }
        if (!("budget_used" in $$source)) {
            this["budget_used"] = 0;
        }
        if (!("budget_total" in $$source)) {
            this["budget_total"] = 0;
        }
        if (!("days_remaining" in $$source)) {
            this["days_remaining"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * UserInfo represents user information for the frontend
 */
export class UserInfo {
    /**
     * student, ta, professor, admin
     */
    "role": string;
    "username": string;
    "project": string;
    "permissions": string[];

    /** Creates a new UserInfo instance. */
    constructor($$source: Partial<UserInfo> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UserInfo {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField3_0($$parsedSource["permissions"]);
        }
        return new UserInfo($$parsedSource as Partial<UserInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
