// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DCVService provides NICE DCV remote desktop functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseDCVConnection closes a DCV connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseDCVConnection(connectionID) {
    return $Call.ByID(1730428496, connectionID);
}

/**
 * ConnectDCV initiates a DCV connection to a user's instance
 * @param {string} username
 * @param {string} project
 * @param {$models.DCVQuality} quality
 * @returns {$CancellablePromise<$models.DCVConnectionInfo | null>}
 */
export function ConnectDCV(username, project, quality) {
    return $Call.ByID(4141042570, username, project, quality).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetDCVConnectionInfo returns information about a specific DCV connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.DCVConnectionInfo | null>}
 */
export function GetDCVConnectionInfo(connectionID) {
    return $Call.ByID(4186662616, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LaunchDCVViewer launches the appropriate DCV viewer for the platform
 * @param {string} connectionID
 * @param {$models.DCVQuality} quality
 * @returns {$CancellablePromise<void>}
 */
export function LaunchDCVViewer(connectionID, quality) {
    return $Call.ByID(4048216605, connectionID, quality);
}

/**
 * ListDCVConnections returns all active DCV connections
 * @returns {$CancellablePromise<($models.DCVConnectionInfo | null)[]>}
 */
export function ListDCVConnections() {
    return $Call.ByID(724056703).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DCVConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
