// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFRService provides the main service interface for the GUI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectToInstance returns SSH connection information
 */
export function ConnectToInstance(username: string, project: string): $CancellablePromise<string> {
    return $Call.ByID(3413776704, username, project);
}

/**
 * GetProjectInfo delegates to the API
 */
export function GetProjectInfo(project: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(2444192161, project).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUserRole delegates to the API
 */
export function GetUserRole(): $CancellablePromise<$models.UserInfo | null> {
    return $Call.ByID(2160639299).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListInstances delegates to the API
 */
export function ListInstances(project: string): $CancellablePromise<($models.InstanceInfo | null)[]> {
    return $Call.ByID(149332392, project).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * StartInstance delegates to the API
 */
export function StartInstance(instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(1903254735, instanceName);
}

/**
 * StopInstance delegates to the API
 */
export function StopInstance(instanceName: string): $CancellablePromise<void> {
    return $Call.ByID(535795755, instanceName);
}

// Private type creation functions
const $$createType0 = $0.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $0.UserInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $0.InstanceInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
