// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFRService provides the main service interface for the GUI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectToInstance returns SSH connection information
 * @param {string} username
 * @param {string} project
 * @returns {$CancellablePromise<string>}
 */
export function ConnectToInstance(username, project) {
    return $Call.ByID(3413776704, username, project);
}

/**
 * GetProjectInfo delegates to the API
 * @param {string} project
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function GetProjectInfo(project) {
    return $Call.ByID(2444192161, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetUserRole delegates to the API
 * @returns {$CancellablePromise<$models.UserInfo | null>}
 */
export function GetUserRole() {
    return $Call.ByID(2160639299).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListInstances delegates to the API
 * @param {string} project
 * @returns {$CancellablePromise<($models.InstanceInfo | null)[]>}
 */
export function ListInstances(project) {
    return $Call.ByID(149332392, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StartInstance delegates to the API
 * @param {string} instanceName
 * @returns {$CancellablePromise<void>}
 */
export function StartInstance(instanceName) {
    return $Call.ByID(1903254735, instanceName);
}

/**
 * StopInstance delegates to the API
 * @param {string} instanceName
 * @returns {$CancellablePromise<void>}
 */
export function StopInstance(instanceName) {
    return $Call.ByID(535795755, instanceName);
}

// Private type creation functions
const $$createType0 = $0.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $0.UserInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $0.InstanceInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
