// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../../github.com/scttfrdmn/lfr-tools/pkg/api/models.js";

export const InstanceInfo = api$0.InstanceInfo;
export type InstanceInfo = api$0.InstanceInfo;

export const ProjectInfo = api$0.ProjectInfo;
export type ProjectInfo = api$0.ProjectInfo;

/**
 * ProjectStatusUpdate represents project-level changes
 */
export class ProjectStatusUpdate {
    "name": string;
    "students_online": number;
    "budget_used": number;
    "alert_count": number;

    /** Creates a new ProjectStatusUpdate instance. */
    constructor($$source: Partial<ProjectStatusUpdate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("students_online" in $$source)) {
            this["students_online"] = 0;
        }
        if (!("budget_used" in $$source)) {
            this["budget_used"] = 0;
        }
        if (!("alert_count" in $$source)) {
            this["alert_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectStatusUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectStatusUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectStatusUpdate($$parsedSource as Partial<ProjectStatusUpdate>);
    }
}

/**
 * SSHConnectionInfo represents connection information for frontend
 */
export class SSHConnectionInfo {
    "id": string;
    "connected": boolean;
    "public_ip": string;
    "username": string;

    /** Creates a new SSHConnectionInfo instance. */
    constructor($$source: Partial<SSHConnectionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("public_ip" in $$source)) {
            this["public_ip"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectionInfo($$parsedSource as Partial<SSHConnectionInfo>);
    }
}

/**
 * Type aliases for frontend compatibility
 */
export const UserInfo = api$0.UserInfo;

/**
 * Type aliases for frontend compatibility
 */
export type UserInfo = api$0.UserInfo;
