// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../../github.com/scttfrdmn/lfr-tools/pkg/api/models.js";

/**
 * DCVConnectionInfo represents DCV connection information for frontend
 */
export class DCVConnectionInfo {
    /**
     * Creates a new DCVConnectionInfo instance.
     * @param {Partial<DCVConnectionInfo>} [$$source = {}] - The source object to create the DCVConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("public_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_ip"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("dcv_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dcv_port"] = 0;
        }
        if (!("viewer_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["viewer_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DCVConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DCVConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DCVConnectionInfo(/** @type {Partial<DCVConnectionInfo>} */($$parsedSource));
    }
}

/**
 * DCVQuality represents DCV connection quality settings
 * @readonly
 * @enum {string}
 */
export const DCVQuality = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DCVQualityLow: "low",
    DCVQualityMedium: "medium",
    DCVQualityHigh: "high",
    DCVQualityLossless: "lossless",
};

export const InstanceInfo = api$0.InstanceInfo;

/**
 * @typedef {api$0.InstanceInfo} InstanceInfo
 */

export const ProjectInfo = api$0.ProjectInfo;

/**
 * @typedef {api$0.ProjectInfo} ProjectInfo
 */

/**
 * ProjectStatusUpdate represents project-level changes
 */
export class ProjectStatusUpdate {
    /**
     * Creates a new ProjectStatusUpdate instance.
     * @param {Partial<ProjectStatusUpdate>} [$$source = {}] - The source object to create the ProjectStatusUpdate.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("students_online" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["students_online"] = 0;
        }
        if (!("budget_used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budget_used"] = 0;
        }
        if (!("alert_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alert_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectStatusUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectStatusUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectStatusUpdate(/** @type {Partial<ProjectStatusUpdate>} */($$parsedSource));
    }
}

/**
 * SSHConnectionInfo represents connection information for frontend
 */
export class SSHConnectionInfo {
    /**
     * Creates a new SSHConnectionInfo instance.
     * @param {Partial<SSHConnectionInfo>} [$$source = {}] - The source object to create the SSHConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("public_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_ip"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectionInfo(/** @type {Partial<SSHConnectionInfo>} */($$parsedSource));
    }
}

/**
 * Type aliases for frontend compatibility
 */
export const UserInfo = api$0.UserInfo;

/**
 * Type aliases for frontend compatibility
 * @typedef {api$0.UserInfo} UserInfo
 */
