// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitoringService provides real-time status monitoring
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetProjectStatus returns current project status
 */
export function GetProjectStatus(project: string): $CancellablePromise<$models.ProjectStatusUpdate | null> {
    return $Call.ByID(1001952643, project).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RefreshInstanceStatus manually refreshes instance status for a project
 */
export function RefreshInstanceStatus(project: string): $CancellablePromise<void> {
    return $Call.ByID(3533490410, project);
}

/**
 * StartMonitoring begins real-time status monitoring
 */
export function StartMonitoring(projects: string[]): $CancellablePromise<void> {
    return $Call.ByID(1003383102, projects);
}

/**
 * StopMonitoring stops real-time monitoring
 */
export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(3167359282);
}

/**
 * SubscribeToProject subscribes to updates for a specific project
 */
export function SubscribeToProject(project: string): $CancellablePromise<void> {
    return $Call.ByID(2264251386, project);
}

// Private type creation functions
const $$createType0 = $models.ProjectStatusUpdate.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
