// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHProxyService provides WebSocket SSH proxy functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../../github.com/scttfrdmn/lfr-tools/pkg/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseConnection closes an SSH connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseConnection(connectionID) {
    return $Call.ByID(2514428260, connectionID);
}

/**
 * ConnectStudent provides simplified connection for students
 * @param {string} username
 * @param {string} project
 * @returns {$CancellablePromise<$models.SSHConnectionInfo | null>}
 */
export function ConnectStudent(username, project) {
    return $Call.ByID(2796028797, username, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExecuteCommand executes a command via SSH and returns the output
 * @param {string} connectionID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteCommand(connectionID, command) {
    return $Call.ByID(1772448060, connectionID, command);
}

/**
 * InitiateSSHConnection starts an SSH connection to a user's instance
 * @param {string} username
 * @param {string} project
 * @returns {$CancellablePromise<$models.SSHConnectionInfo | null>}
 */
export function InitiateSSHConnection(username, project) {
    return $Call.ByID(552860267, username, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListConnections returns all active SSH connections
 * @returns {$CancellablePromise<($models.SSHConnectionInfo | null)[]>}
 */
export function ListConnections() {
    return $Call.ByID(1594403193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * StartInstanceIfNeeded starts an instance if it's not running
 * @param {string} username
 * @param {string} project
 * @returns {$CancellablePromise<api$0.InstanceInfo | null>}
 */
export function StartInstanceIfNeeded(username, project) {
    return $Call.ByID(2870373065, username, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * StartInteractiveSession starts an interactive SSH session
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function StartInteractiveSession(connectionID) {
    return $Call.ByID(2198879388, connectionID);
}

// Private type creation functions
const $$createType0 = $models.SSHConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = api$0.InstanceInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
