// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHProxyService provides WebSocket SSH proxy functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../../github.com/scttfrdmn/lfr-tools/pkg/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseConnection closes an SSH connection
 */
export function CloseConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2514428260, connectionID);
}

/**
 * ConnectStudent provides simplified connection for students
 */
export function ConnectStudent(username: string, project: string): $CancellablePromise<$models.SSHConnectionInfo | null> {
    return $Call.ByID(2796028797, username, project).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteCommand executes a command via SSH and returns the output
 */
export function ExecuteCommand(connectionID: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(1772448060, connectionID, command);
}

/**
 * InitiateSSHConnection starts an SSH connection to a user's instance
 */
export function InitiateSSHConnection(username: string, project: string): $CancellablePromise<$models.SSHConnectionInfo | null> {
    return $Call.ByID(552860267, username, project).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListConnections returns all active SSH connections
 */
export function ListConnections(): $CancellablePromise<($models.SSHConnectionInfo | null)[]> {
    return $Call.ByID(1594403193).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * StartInstanceIfNeeded starts an instance if it's not running
 */
export function StartInstanceIfNeeded(username: string, project: string): $CancellablePromise<api$0.InstanceInfo | null> {
    return $Call.ByID(2870373065, username, project).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * StartInteractiveSession starts an interactive SSH session
 */
export function StartInteractiveSession(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2198879388, connectionID);
}

// Private type creation functions
const $$createType0 = $models.SSHConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = api$0.InstanceInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
